# Generated by Django 4.2.7 on 2023-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiles',
            options={'verbose_name': 'Mobile'},
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='image',
            field=models.ImageField(default='photos/1.1.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
