# Generated by Django 4.2.7 on 2023-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sign',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
